//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TriphulcasMvc.MVCCustomResources.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenido: utiliza la barra superior para editar, guardar y publicar.
        /// </summary>
        public static string ArticleContent {
            get {
                return ResourceManager.GetString("ArticleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introducción: breve descripción del artículo (opcional).
        /// </summary>
        public static string ArticleIntroduction {
            get {
                return ResourceManager.GetString("ArticleIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título: este campo es obligatorio.
        /// </summary>
        public static string ArticleTitle {
            get {
                return ResourceManager.GetString("ArticleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido, {0}!.
        /// </summary>
        public static string AuthenticationWelcomeMessage {
            get {
                return ResourceManager.GetString("AuthenticationWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAAFpNnJPsWoBAEa0Unb56xAfuK35GdnAsZAhDusBgMLCSZAeFLm1PDZBphaZCXLg1bsOYFnpDmLO1ijtV8K1I04lddKAw7F0WZAn9e46cggZDZD.
        /// </summary>
        public static string DefaultAccessToken {
            get {
                return ResourceManager.GetString("DefaultAccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string EditArticle {
            get {
                return ResourceManager.GetString("EditArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, modifica tu artículo haciendo click en este botón:.
        /// </summary>
        public static string EditArticleDescription {
            get {
                return ResourceManager.GetString("EditArticleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://graph.facebook.com/{0}/picture?type=large.
        /// </summary>
        public static string FacebookLargePictureUrl {
            get {
                return ResourceManager.GetString("FacebookLargePictureUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://graph.facebook.com/{0}/picture.
        /// </summary>
        public static string FacebookPictureUrl {
            get {
                return ResourceManager.GetString("FacebookPictureUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://graph.facebook.com/{0}/picture?type=small.
        /// </summary>
        public static string FacebookSmallPictureUrl {
            get {
                return ResourceManager.GetString("FacebookSmallPictureUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://graph.facebook.com/{0}/picture?type=square.
        /// </summary>
        public static string FacebookSquarePictureUrl {
            get {
                return ResourceManager.GetString("FacebookSquarePictureUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Últimos artículos.
        /// </summary>
        public static string LastArticles {
            get {
                return ResourceManager.GetString("LastArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasta pronto!.
        /// </summary>
        public static string SeeYou {
            get {
                return ResourceManager.GetString("SeeYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vuelve a vernos.
        /// </summary>
        public static string SnippetComebackBeforeLink {
            get {
                return ResourceManager.GetString("SnippetComebackBeforeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cuando quieras.
        /// </summary>
        public static string SnippetComebackLink {
            get {
                return ResourceManager.GetString("SnippetComebackLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nos gusta saber quién nos visita, enséñanos tu cara con.
        /// </summary>
        public static string SnippetShowFaceBeforeLink {
            get {
                return ResourceManager.GetString("SnippetShowFaceBeforeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tu cuenta de facebook.
        /// </summary>
        public static string SnippetShowFaceLink {
            get {
                return ResourceManager.GetString("SnippetShowFaceLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido triphulcas! Nos alegramos de verte..
        /// </summary>
        public static string SnippetTriphulcasWelcomeMessage {
            get {
                return ResourceManager.GetString("SnippetTriphulcasWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nos salen granos de verte..
        /// </summary>
        public static string SnippetWelcomeMessage {
            get {
                return ResourceManager.GetString("SnippetWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido .
        /// </summary>
        public static string SnippetWelcomeTitle {
            get {
                return ResourceManager.GetString("SnippetWelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menú del día:.
        /// </summary>
        public static string TitleMainSnippet {
            get {
                return ResourceManager.GetString("TitleMainSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vuelve a intentarlo más tarde..
        /// </summary>
        public static string TryAgainLater {
            get {
                return ResourceManager.GetString("TryAgainLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, sigue dañando tu imagen subiendo más fotos haciendo click .
        /// </summary>
        public static string UploadImagesDescription {
            get {
                return ResourceManager.GetString("UploadImagesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquí.
        /// </summary>
        public static string UploadImagesLiteral {
            get {
                return ResourceManager.GetString("UploadImagesLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to correcta.
        /// </summary>
        public static string WithoutProblems {
            get {
                return ResourceManager.GetString("WithoutProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to con problemas.
        /// </summary>
        public static string WithProblems {
            get {
                return ResourceManager.GetString("WithProblems", resourceCulture);
            }
        }
    }
}
